package View;

import Controller.LoginController;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Dani
 */
public class Login extends javax.swing.JFrame {

    private final LoginController controller;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null); // Centraliza a janela na tela
        this.setTitle("Sistema Biblioteca - Login"); // Define o título
        controller = new LoginController(this);

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        labelCadastroCliente = new javax.swing.JLabel();
        LabelNome = new javax.swing.JLabel();
        LabelEmail = new javax.swing.JLabel();
        TextLogin = new javax.swing.JTextField();
        butEntrar = new javax.swing.JButton();
        TextSenha = new javax.swing.JPasswordField();
        painelCadastro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagem/log_menor.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, 30));

        labelCadastroCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelCadastroCliente.setText("Login Administrador");
        getContentPane().add(labelCadastroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        LabelNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelNome.setText("Usuario");
        getContentPane().add(LabelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, -1));

        LabelEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelEmail.setText("Senha");
        getContentPane().add(LabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 40, -1));

        TextLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextLoginActionPerformed(evt);
            }
        });
        getContentPane().add(TextLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 200, 40));

        butEntrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butEntrar.setText("Entrar");
        butEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(butEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, 200, 30));
        getContentPane().add(TextSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 200, 40));

        painelCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagem/fundo1.png"))); // NOI18N
        painelCadastro.setText("jLabel2");
        getContentPane().add(painelCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 370, 510));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagem/book1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1103, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butEntrarActionPerformed

        try {
            this.controller.autenticar();
        } catch (ParseException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_butEntrarActionPerformed

    private void TextLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
          
                    new Login().setVisible(true);

            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JTextField TextLogin;
    private javax.swing.JPasswordField TextSenha;
    private javax.swing.JButton butEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel labelCadastroCliente;
    private javax.swing.JLabel painelCadastro;
    // End of variables declaration//GEN-END:variables
    
    public void mostrarMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);

    }

    public JTextField getTextLogin() {
        return TextLogin;
    }

    public void setTextLogin(JTextField TextLogin) {
        this.TextLogin = TextLogin;
    }

    public JPasswordField getTextSenha() {
        return TextSenha;
    }

    public void setTextSenha(JPasswordField TextSenha) {
        this.TextSenha = TextSenha;
    }

    
    

}
