/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.MenuController;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Dani
 */
public class Menu extends javax.swing.JFrame {

    private final MenuController controller;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setTitle("Sistema Biblioteca - Menu Principal"); // Define o título
        setLocationRelativeTo(null); // Centraliza a janela na tela

        this.controller = new MenuController(this);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        butMulta = new javax.swing.JButton();
        butListagem = new javax.swing.JButton();
        butEmprestimo = new javax.swing.JButton();
        butDevolucao = new javax.swing.JButton();
        butCadastro = new javax.swing.JButton();
        butLogin = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Logout Adm");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 580, 100, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("Gestão Multas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 255));
        jLabel8.setText("Empréstimo Livro");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setText(" Listagem Livros");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 580, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("Devolução Livro");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagem/log_menor.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, 30));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Cadastro Usuário");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 580, -1, -1));

        jLabel5.setFont(new java.awt.Font("Imprint MT Shadow", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("S I S T E M A   B I B L I O T E C Á R I O");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 580, -1));

        butMulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagem/icon_dev.png"))); // NOI18N
        butMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butMultaActionPerformed(evt);
            }
        });
        getContentPane().add(butMulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, 200, 160));

        butListagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagem/icon_list.png"))); // NOI18N
        butListagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butListagemActionPerformed(evt);
            }
        });
        getContentPane().add(butListagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 200, 160));

        butEmprestimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagem/icon_emp.png"))); // NOI18N
        butEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butEmprestimoActionPerformed(evt);
            }
        });
        getContentPane().add(butEmprestimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 200, 160));

        butDevolucao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagem/icon_dev.png"))); // NOI18N
        butDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDevolucaoActionPerformed(evt);
            }
        });
        getContentPane().add(butDevolucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 200, 160));

        butCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagem/icon_cad.png"))); // NOI18N
        butCadastro.setToolTipText("");
        butCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(butCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 200, 160));

        butLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagem/logout.png"))); // NOI18N
        butLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLoginActionPerformed(evt);
            }
        });
        getContentPane().add(butLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 450, 200, 160));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagem/po.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 970, 640));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagem/book1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1278, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCadastroActionPerformed
        try {
            this.controller.navegarParaCadastro();
        } catch (ParseException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                // Fechar a tela de menu
        dispose();
    }//GEN-LAST:event_butCadastroActionPerformed

    private void butListagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butListagemActionPerformed
                try {
            this.controller.navegarParaListagem();
        } catch (ParseException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
                
                        // Fechar a tela de menu
        dispose();
    }//GEN-LAST:event_butListagemActionPerformed

    private void butLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLoginActionPerformed
    
        try {
            this.controller.navegarParaLogin();
        } catch (ParseException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                // Fechar a tela de menu
        dispose();
 
    }//GEN-LAST:event_butLoginActionPerformed

    private void butEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butEmprestimoActionPerformed
        // TODO add your handling code here:
                try {
            this.controller.navegarParaEmprestimo();
        } catch (ParseException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
   
                        // Fechar a tela de menu
        dispose();
    }//GEN-LAST:event_butEmprestimoActionPerformed

    private void butMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butMultaActionPerformed
        try {
            this.controller.navegarParaMultas();
        } catch (ParseException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
           // Fechar a tela de menu
        dispose();

    }//GEN-LAST:event_butMultaActionPerformed

    private void butDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDevolucaoActionPerformed
        try {
            this.controller.navegarParaDevolucao();
        } catch (ParseException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
           // Fechar a tela de menu
        dispose();
    }//GEN-LAST:event_butDevolucaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCadastro;
    private javax.swing.JButton butDevolucao;
    private javax.swing.JButton butEmprestimo;
    private javax.swing.JButton butListagem;
    private javax.swing.JButton butLogin;
    private javax.swing.JButton butMulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
